#!/bin/sh
# shellcheck disable=SC2034
ln -s /jffs/addons/ntpmerlin.d/timeserverd /opt/bin 2>/dev/null
chmod 0755 /opt/bin/timeserverd

if [ "$1" = "stop" ] || [ "$1" = "kill" ]; then
	killall -q timeserverd
	killall -q chronyd
	sleep 5
fi


ENABLED=yes
PROCS=timeserverd
ARGS="S77chronyd"
PREARGS=""
PRECMD="killall ntp && killall ntpd"
POSTCMD=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
