#!/bin/sh

# shellcheck disable=SC2034

if [ "$1" = "start" ] || [ "$1" = "restart" ]; then
	# Wait for NTP before starting
	logger -st "S77ntpd" "Waiting for NTP to sync before starting..."
	ntptimer=0
	while [ "$(nvram get ntp_ready)" = "0" ] && [ "$ntptimer" -lt "300" ]; do
		ntptimer=$((ntptimer+1))
		sleep 1
	done

	if [ "$ntptimer" -ge "300" ]; then
		logger -st "S77ntpd" "NTP failed to sync after 5 minutes - please check immediately!"
		echo ""
		exit 1
	fi
fi

ENABLED=yes
PROCS=ntpd
ARGS="-c /jffs/configs/ntp.conf -g"
PREARGS=""
PRECMD="killall ntp"
POSTCMD="/jffs/scripts/ntpmerlin generate"
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
